apiVersion: apps/v1
kind: Deployment
metadata: 
  name: keel-test
  annotations:
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 1m"
  labels: 
    name: "keel-test"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: keel-test
  template:
    metadata:
      name: keel-test
      labels:
        app: keel-test
    spec:     
      containers:                    
        - image: jhaineault/keel-test:latest
          imagePullPolicy: Always # this is required to force pull image     
          name: keel-test
          ports:
            - containerPort: 8500
          livenessProbe:
            httpGet:
              path: /
              port: 8500
            initialDelaySeconds: 10
            timeoutSeconds: 5